# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bcf6dc62ba0444a6a1a8865dbc683449744c4adaee49cd5e4e3dfc918489efdbb88489f6f28afe8909652ed3cc75e0a2537853d808befb06c0221ec3b3369ba

test:
  secret_key_base: fe2ba748d064eb072838c2b67301eb735ee067b3d250cb249d5081631e8e6baf9880522717103b7986a5ea832d02329dfe1474737cac0a62af4cf93cbd3f451e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
